/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chenqiwei_tools_Jni */

#ifndef _Included_com_chenqiwei_tools_Jni
#define _Included_com_chenqiwei_tools_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chenqiwei_tools_Jni
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chenqiwei_tools_Jni_version(JNIEnv *env, jclass cls)
{
	return (*env)->NewStringUTF(env, "version 0.1");
}

#ifdef __cplusplus
}
#endif
#endif
